### ISSUE TITLE
YouTube url Checking

### ISSUE THREAD

**Issue by iim-ayush** [Atkion/andkion#1]
https://github.com/Atkion/andkion/blob/0b3f1f6811c78f99fc54100f76fbbca9fff2b3e9/modules/musicPlayer.js#L126-L134

You can use [video_basic_info](https://github.com/play-dl/play-dl/blob/1cfaf52945a3fb3c386f10dbf05dfb381819434a/play-dl/YouTube/utils/extractor.ts#L10) since you are checking url only. video_info deciphers formats also, so it might take more time.

**Comment by Atkion** [comment]
Good call, thanks.

**Comment by iim-ayush** [comment]
@Atkion 

You can also use this feature, much faster and more reliable [validate](https://github.com/play-dl/play-dl/tree/main#validate)

Only available on latest 0.7.0 update
